### PR TITLE
Don't clean raw channel labels and fix/refactor rereferencing

### PR DESCRIPTION
**Pull request by TomBugnon**
Use channel labels as provided by user or loaded from data, without "cleaning", in ReadSleep

### CODE REVIEW

**Comment by TomBugnon** [comment]
By the way I think the failed integration checks are unrelated to these commits

**Comment by EtienneCmb** [comment]
Hello @TomBugnon ,

Sorry I'm very busy those times. The cleaning step is needed for re-referencing (e.g bipolarization). Non-expert users are going to provide a file (like edf) and they are not going to manually edit the channel names. IMO it's better to keep this cleaning step.

Does it make a difference on your data?

**Comment by EtienneCmb** [comment]
about the tests, can you try to rebase your master onto the visbrain one? Because I can see that there's issues related to scikit-image and if I remember correctly I fixed it in the past

**Comment by TomBugnon** [comment]
@EtienneCmb Oh I see, I didn't think of this.

The way we use it is that we preload some LFP, EEG and EMG data and pass it to Sleep along with channel labels. Because of the string stripping the result looks like this.
image
It's not that big a deal but it would be nice to have to possibility to use the raw channel names. @raphaelvallat  told me he had thought of removing the channel cleaning altogether already and I could go for it.
Another option could be to clean the channel labels only if they were not passed by the user during the sleep call, but I'm not sure how to deal with the re-referencing

**Comment by raphaelvallat** [comment]
I may be wrong but I think only a very small fraction of users actually use the bipolarization function in SLEEP (I never use it). And I agree with @TomBugnon that it's better to have the full channel names. So, what about applying the cleaning only when the user applies the bipolar re-referencing?

**Comment by EtienneCmb** [comment]
Ok, I'll also merge this PR once the tests are good

**Comment by TomBugnon** [comment]
Hi guys @EtienneCmb @raphaelvallat ,
Some progress on this. Delving in the code I ended up making changes a bit beyond those originally planned:

1. I moved the channel "cleaning" step so that it only happens during bipolar re-referencing. Otherwise the raw channel names are used 
2. During bipolar rereferencing, I changed the way that channel number and channel names are parsed, so that the LAST string of digits rather than first is used. It shouldn't change anything in most case but I thought it could be useful in come (eg if channels are indexed as follows: EEG1,1, EEG1,2, EEG2,1, ..., the bipolarisation happens amongst EEG1 and EEG2 stores independently). 
3. "non-eeg" channels are now found based on the presence of patterns anywhere in the channel string rather than at the start of the string, and I added "lfp" to the list of dismissed patterns
4. Finally, I fixed a __bug that led to the wrong channel being used for re-referencing__, because the index of the channel passed to `rereference()` was the index amongst the list of eeg channels, rather than the list of all channels. This also interacted wrongly with the addition of channels in the "Add channels to ignore during re-referencing"

Let me know if you think I should remove some of those or break down in different PRs.

Finally the travis test that fails is the same as in the other PR, the `scikit-image` issue that I couldn't figure out.

Cheers, T

**Comment by raphaelvallat** [comment]
Thanks so much for this @TomBugnon ! The re-referencing issue is indeed critical, so I think we should merge your PR and release a new version quickly @EtienneCmb. Ok with the other changes. Thanks again.

**Comment by EtienneCmb** [comment]
@TomBugnon I fixed visbrain's issues, all light are green for merging :)

Thank you for this first PR, let's move to the big one

**Pull request merged**
