### PR TITLE
Decouple scoring window from display window

### PR DESCRIPTION
**Pull request by TomBugnon**
Hi @EtienneCmb  @raphaelvallat 
This PR starts to address https://github.com/EtienneCmb/visbrain/issues/35 so as to make Sleep  usable for animal sleep scoring. The two main changes are:

- The implementation of a 'scoring window', centered within the display window, that is used for setting the hypnogram stage and annotations. 
    - The scoring window can be displayed  by movable indicator bars (`ScorWinIndicator`) added to each channel plot. The location and width (in data coordinates) of the bars are updated when moving the display or scoring window
    - There is a "locking" checkbox that (amongst other) makes the scoring window size and slider stepsize follow the window size. If unchecked, the scor size can be smaller than the window size and the stepsize follows the scoring window size

- The implementation of a "Window hypnogram", which is pretty much a copy-paste of the Hypnogram canvas except its camera follows the display window. The internal data of the window hypnogram and "pan"-hypnogram are not enforced to be the same, but the changes to the pan-hypnogram are applied similarly to the window-hyp. It does the trick

Possible TODO:
- Deal with the scoring of the very start and very end of the recording which is a bit of a rough edge for now (since the scoring window is always centered) ? 
- resize the hypnogram(s) (make them a bit smaller)?
- Clarify how the different settings interact in ui_settings.py ?
- Make the window hypnogram inherit the data from the pan hypnogram so that we don't have to duplicate the data-settings amongst window and pan hypnogram as is the case right now (implementation detail) 

Cheers

### CODE REVIEW

**Comment by TomBugnon** [comment]
I fixed a bug, added the tests and updated the documentation source files (however I didn't build the doc)
Let me know if you'd need anything more @raphaelvallat @EtienneCmb

**Comment by raphaelvallat** [comment]
Hi @TomBugnon! Apologies for the late reply, and first let me say congratulations on this really impressive work. I've just tried the new scoring window and it looks great. Documentation and code are very neat too (but I'll let @EtienneCmb have a closer look at the latter). Two quick comments:

1) Do we really need to have a "Window hypnogram", when the users can simply use the "Zoom" mode (shortcut = Z) to have exactly the same output, as shown in the screenshot below? I understand that it may still be useful to visualize the full-night hypnogram in addition to the current window hypnogram, but just wondering if we could gain in simplicity here.

image

2) Travis CI is failing for the standard test (dependency error with scikit-image) and the flake8/PEP8 test. Could you try to fix both and make sure that your code follows the PEP8 style?

Thanks again!

**Comment by TomBugnon** [comment]
Hi @raphaelvallat thanks a lot for the feedback!

I hadn't even noticed that there was a Zoom mode which does precisely the trick... I think it is sufficient indeed.

I removed the "Window Hypnogram", updated the doc and cleaned the code for flake8 compliance.

As for the Travis CI error, I don't think this has anything to do with my changes actually, because  there is the same error when running a build on the master branch (and I didn't modify anything related to the imports, the travis settings, or the tests that fail). I don't know why that is... Maybe related to the Warning message when calling pip during the install? Anyway I think it's unrelated to my commits : 

> $ if [ "${TEST}" == "standard" ] || [ "${TEST}" == "examples" ]; then pip install codecov pytest pytest-cov pytest-sugar pytest-travis-fold pytest-faulthandler openpyxl xlrd; pip install mne nibabel pandas tensorpac scikit-image imageio lxml; pip install git+https://github.com/hbldh/lspopt.git#egg=lspopt; fi;
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

**Comment by TomBugnon** [comment]
By the way, just a reminder that 
- I haven't installed the sphinx documentation
- I changed the documentation images only where relevant, so there's a mix between the old and new version of the GUI in the documentation (not a big deal I guess?)

**Comment by raphaelvallat** [comment]
Thanks for the new commits @TomBugnon! Agree for the documentation, I think we can make the final changes once we've merged to the master (and Etienne will probably the one compiling the final version anyway). Oh, I see for Travis. @EtienneCmb any ideas why it is failing?

Other than that, happy to approve the merge! Thanks

**Comment by TomBugnon** [comment]
ping @EtienneCmb  :)

**Comment by EtienneCmb** [comment]
Hi @TomBugnon ,

As @raphaelvallat , apologizes for the delayed answer. Indeed you made a beautiful work with this PR.

Travis is failing probably because your master doesn't includes the scikit-image fix (I made it a few month ago if I remember correctly). Can you try to rebase your master and see if the travis tests are good?

Thanks again for your commits, it represents a lot of work !

**Comment by TomBugnon** [comment]
@EtienneCmb Thanks !

I'm sorry I can't seem to figure out the issue with travis. My origin/scoring_window branch is up to date already with upstream/master (at the 'oups' `0238d8f7` commit).  I'm not sure in what commit the scikit-image fix you're talking about is, is it in develop? From reading the .travis.yml  it seems like `pip install scikit-image` should be called during the travis install.

**Comment by EtienneCmb** [comment]
> at the 'oups' 0238d8f7  commit

:D

Yes, scikit-image should be installed and it should not failed because of this. I discussed with Raph, we are both agree that this PR should be accepted. I'll try to dig into this scikit-image issue asap and your PR should pass the tests then (or at least not failing because of scikit-image).

Also, can you please add your modifications to the [release.rst](https://github.com/EtienneCmb/visbrain/blob/master/docs/release.rst)?

**Comment by TomBugnon** [comment]
I changed version (or did you want me to add the changes to v0.4.5?)

**Comment by EtienneCmb** [comment]
Perfect. Please undo your modifications to the abstract. This a published paper and it's important to keep the version intact

**Comment by TomBugnon** [comment]
Right

**Comment by EtienneCmb** [comment]
@TomBugnon I merged #63, and you changed the `release.rst` inside your PR. Can you please rebase this PR on the latest master and make sure that your modifications are present in the `release.rst`?

**Comment by TomBugnon** [comment]
I rebased everything to upstream/master, should be all good now @EtienneCmb 

The latest visbrain version is now  0.4.6, starring the shiny new feature _Allow decoupling of the `scoring_window` and `display_window` to facilitate scoring of animal data in shorter epochs_

**Comment by EtienneCmb** [comment]
@raphaelvallat can you please take a final look of Tom's modifications? Everything seems to be ready for merging. It would be great to merge this PR today

**Comment by EtienneCmb** [comment]
@TomBugnon thanks again for this amazing PR. If #35 is fixed, can you please close it?

**Comment by TomBugnon** [comment]
Thanks guys! Let's keep 35 open as a place to discuss other upcoming changes for generalization of Sleep to animal scoring, there'd be more work to do (eg flexible state definition)

**Comment by EtienneCmb** [comment]
flexible states represents a lot of work since the current static definition is really really deeply integrated inside sleep

**Pull request merged**
